Добавил возможность изменять имя сессии
DirectumCompany/Yotalab.PlanningPoker pull request #22
Opened 2021-03-06 14:48 UTC by LDC7

Думаю в этой модалке потом можно будет расположить ещё какие-то настройки сессии.
Именование не очень нравится, но что-то другое в голову не приходит.

2021-03-07 15:55 UTC, hankir requested changes
Пока так. По диагонали потестил, все работает.

2021-03-07 15:55 UTC, hankir commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/Components/SessionOptionsModal.razor
> +  public Func<ChangeSessionOptionsArgs, Task> OnConfirm { get; set; }
Тут надо использовать EventCallback\<ChangeSessionOptionsArgs\>, и в обработчиках переданных в этот параметр не нужено будет вызывать StateHasChanged.

См. https://docs.microsoft.com/ru-ru/aspnet/core/blazor/components/event-handling?view=aspnetcore-3.1#eventcallback

2021-03-07 15:55 UTC, hankir commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/Components/SessionOptionsModal.razor
> +      return this.JS.InvokeVoidAsync("alert", "Имя сессии не может быть пустым!").AsTask();
Давай лучше переделаем на валидацию вместо алерта.
Вверху содержимого модалки добавить блок \<div class="alert"\>...\</div\> и показывает его если есть ошибка ввода.

2021-03-07 15:55 UTC, hankir commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/Components/SessionOptionsModal.razor
> +﻿@using Yotalab.PlanningPoker.BlazorServerSide.Services.Args
Вместо SessionOptionsModal -> EditSessionModal?

2021-03-07 15:55 UTC, hankir commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/SessionCard.razor
> +      <img class="btn h-100" src="img/edit_icon.svg" data-bs-toggle="modal" data-bs-target="#sessionOptionsModal" />
Надо избавиться от svg иконок, на мой взгляд, шрифтовые иконки удобнее. К проекту подключены open-iconic, давай заюзаем их. Потом надо будет от коронки и пинка еще избавиться, но можно отдельно, могу сам потом залить.
В варианте с шрифтовой иконкой карандашик выгладел бы так:
      \<button class="btn h-100" data-bs-toggle="modal" data-bs-target="#sessionOptionsModal"\>
        \<span class="**oi oi-pencil text-warning**"\>\</span\>
      \</button\>

см. https://useiconic.com/open

2021-03-07 15:55 UTC, hankir commented on Yotalab.PlanningPoker.BlazorServerSide/Services/SessionService.cs
> +    public Task EditOptionsAsync(ChangeSessionOptionsArgs args)
EditSessionAsync?

2021-03-07 15:55 UTC, hankir commented on Yotalab.PlanningPoker.Grains.Interfaces/Models/Args/ChangeSessionInfoArgs.cs
> +  public class ChangeSessionInfoArgs
Комментарии по пути можно добавить :)

2021-03-07 15:55 UTC, hankir commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/SessionCard.razor
> +  <SessionOptionsModal Id="sessionOptionsModal" Title="Настройки сессия" Session="@this.session" OnConfirm="@this.ConfirmSessionOptionChangesAsync" />}
Настройка сессия -> Изменение сессии

2021-03-11 18:54 UTC, LDC7 commented on Yotalab.PlanningPoker.BlazorServerSide/Services/SessionService.cs
> +    public Task EditOptionsAsync(ChangeSessionOptionsArgs args)
переименовал

2021-03-11 18:54 UTC, LDC7 commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/SessionCard.razor
> +      <img class="btn h-100" src="img/edit_icon.svg" data-bs-toggle="modal" data-bs-target="#sessionOptionsModal" />
заменил

2021-03-11 18:54 UTC, LDC7 commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/Components/SessionOptionsModal.razor
> +﻿@using Yotalab.PlanningPoker.BlazorServerSide.Services.Args
Переименовал

2021-03-11 18:55 UTC, LDC7 commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/Components/SessionOptionsModal.razor
> +      return this.JS.InvokeVoidAsync("alert", "Имя сессии не может быть пустым!").AsTask();
Сделал алерт.
Там не очень удобно не давать модалке закрываться, если валидация не прошла.
Есть нормальный способ?

2021-03-11 18:55 UTC, LDC7 commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/Components/SessionOptionsModal.razor
> +  public Func<ChangeSessionOptionsArgs, Task> OnConfirm { get; set; }
Поправил

2021-03-11 18:57 UTC, LDC7 commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/SessionCard.razor
> +  <SessionOptionsModal Id="sessionOptionsModal" Title="Настройки сессия" Session="@this.session" OnConfirm="@this.ConfirmSessionOptionChangesAsync" />}
Поменял заголовок

2021-03-11 18:59 UTC, LDC7 commented on Yotalab.PlanningPoker.Grains.Interfaces/Models/Args/ChangeSessionInfoArgs.cs
> +  public class ChangeSessionInfoArgs
Комментарии к классу аргументов? Добавил, но от этого особо лучше не становится.

2021-03-12 09:13 UTC, LDC7 commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/Components/SessionOptionsModal.razor
> +      return this.JS.InvokeVoidAsync("alert", "Имя сессии не может быть пустым!").AsTask();
Могу переделать на BlazoredModal. Ей немножко пользовался.

2021-03-13 06:04 UTC, hankir commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/Components/SessionOptionsModal.razor
> +      return this.JS.InvokeVoidAsync("alert", "Имя сессии не может быть пустым!").AsTask();
Пока не хотелось бы Blazored активно использовать. Он временно для графика прикручен.
Сделай в поле ввода @bind:event="oninput" а на onkeydown валидируй, при пустом вводе можно и кнопку задизаблить и хинт вывести.

2021-03-14 07:31 UTC, LDC7 commented on Yotalab.PlanningPoker.BlazorServerSide/Pages/Components/SessionOptionsModal.razor
> +      return this.JS.InvokeVoidAsync("alert", "Имя сессии не может быть пустым!").AsTask();
\+

2021-03-15 23:50 UTC, hankir approved these changes

2021-03-16 05:13 UTC, merged