Добавлено свойство для состояния сессии - бюллетень голосования, которое позволяет настроить доступный набор карт
DirectumCompany/Yotalab.PlanningPoker pull request #26
Opened 2021-06-14 13:29 UTC by hankir

**Сделано**
Добавлено свойство для состояния сессии - бюллетень голосования, которая представляет набор доступных голосов. Набор доступных голосов можно выбрать при создании сессии или при ее изменении.
Если какие то голоса стали недоступными, то уже зафиксированные голоса сбросятся.

Bulletin - класс, который представляет бюллетень.
BulletinItem - класс представляет элемент бюллетени, который может быть доступен или нет.
По умолчанию сессия создается с набором Фибоначчи, знаком вопроса и чашкой кофе.

Настройка кастомных наборов в этом ПР не поддерживается, только изменение набора по умолчанию.
Возможность изменять набор карт доступных для голосования задается в диалоге редактирования сессии.

**Проверено**
- Проверял старую сессию, что ничего не упадет при ее активации - работает
- Для старой сессии пробовал изменять набор - работает
- Создавал новую сессию, предварительно изменяя набор карт - работает
- Изменял существующую сессию, в том числе снимал все галки с карт - работает.

2021-06-15 13:37 UTC, hankir commented
В классе Vote оказался лишний код, уберу.

2021-06-15 20:27 UTC, hankir commented
> В классе Vote оказался лишний код, уберу.

Убрал

2021-06-19 11:21 UTC, LDC7 requested changes
Возможно стоило бы запретить менять настройки сессии во время голосования.
Ещё кажется, что может не стоит давать удалять все карты.
Но сейчас всё работает, так что можно и так оставить.

2021-06-19 11:21 UTC, LDC7 commented on Yotalab.PlanningPoker.Grains.Interfaces/Models/Bulletin.cs
> +    public Bulletin(Bulletin bulletin)
[мелочь]
Разве в шарпе так принято? Вроде реализуют ICloneable

2021-06-19 11:21 UTC, LDC7 commented on Yotalab.PlanningPoker.Grains/SessionGrain.cs
> +        this.grainState.State.ModeratorIds.Add(moderatorId);
Что если пользователь когда-то был модератором, а после перестал.
А теперь он вновь должен стать модератором после активации?

P.S. Вообще это свойство надо бы обнулять при конвертации.
P.P.S. Когда удалим его?

2021-06-20 07:28 UTC, hankir commented
> Возможно стоило бы запретить менять настройки сессии во время голосования.
> Ещё кажется, что может не стоит давать удалять все карты.
> Но сейчас всё работает, так что можно и так оставить.

Да, специально не парился. Проверил, что работает. Почему бы нет :)
Доработал чутка, чтобы голоса сбрасывались в IDontKnow, когда сессия завершена уже и результаты видны.

2021-06-20 08:05 UTC, LDC7 requested changes

2021-06-20 08:05 UTC, LDC7 commented on Yotalab.PlanningPoker.Grains/SessionGrain.cs
> +        }
А если я убрал из выбора IDontKnown?

2021-06-20 09:11 UTC, LDC7 approved these changes
окей

2021-06-20 09:15 UTC, merged