Добавил отображение количества проголосовавших
DirectumCompany/Yotalab.PlanningPoker pull request #30
Opened 2022-09-20 06:23 UTC by LDC7

Заменил статус "Голосование началось..." на "Проголосовало n/N".
Число проголосовавших передаётся через SessionInfo.
Добавил срабатывание события изменения Сессии при учёте голоса.

2022-09-25 14:33 UTC, hankir commented
Предлагаю ограничиться только UI частью, все данные для этого на клиенте уже есть.
Достаточно будет добавить строчку с кол-вом проголосовавших в заголовок копонента Список участников:
..\Pages\Components\ParticipantsVotesList.razor
Что-то вроде этого:
```
    <MudListSubheader Class="ml-n2 mb-n4">
      <b><span class="text-muted mr-2">@string.Format(UIResources.ParticipantsCount, this.PaticipantVotes.Count())</span></b>
      <b>
        <span class="text-muted mr-2">
          @($"Проголосовало: {this.PaticipantVotes.Count(pair => !Vote.Unset.Equals(pair.Vote))}/{this.PaticipantVotes.Count()}")
        </span>
      </b>
    </MudListSubheader>
```

2022-09-25 14:35 UTC, hankir requested changes

2022-09-25 14:35 UTC, hankir commented on Yotalab.PlanningPoker.Grains.Interfaces/Models/SessionInfo.cs
> +    public int VotesCount { get; set; }
Это визуальная информация, она всегда вычисляется, передавать через грейны смысла нет.

2022-09-25 14:35 UTC, hankir commented on Yotalab.PlanningPoker.Grains/SessionGrain.cs
> +      this.NotifySessionInfoChanged();
Из-за того, что данные о кол-ве голосов стало передаваться в SessionInfo, пришлось делать здесь лишнюю нотификацию.

2022-09-25 14:35 UTC, hankir commented on Yotalab.PlanningPoker.BlazorServerSide/Resources/UIResources.resx
> -    <value>Voting has begun...</value>
В живую не смотрел, но этот статус отображается еще и в списке. Теперь пропало?

2022-10-01 08:17 UTC, LDC7 commented on Yotalab.PlanningPoker.BlazorServerSide/Resources/UIResources.resx
> -    <value>Voting has begun...</value>
не актуально

2022-10-01 08:17 UTC, LDC7 commented on Yotalab.PlanningPoker.Grains/SessionGrain.cs
> +      this.NotifySessionInfoChanged();
не актуально

2022-10-01 08:18 UTC, LDC7 commented on Yotalab.PlanningPoker.Grains.Interfaces/Models/SessionInfo.cs
> +    public int VotesCount { get; set; }
да, но что-то не увидел как получить.
исправил

2022-10-01 08:20 UTC, LDC7 commented on Yotalab.PlanningPoker.Grains.Interfaces/Models/SessionInfo.cs
> +    public int VotesCount { get; set; }
Немного не так сделал как ты предложил.

Зачем нам число участников если его видно после "/".
\+ там есть проблема, что когда голосование завершено, там будет "2/2" (например).
А так с проверкой вроде нормально

2022-10-16 08:29 UTC, hankir approved these changes

2022-10-16 08:29 UTC, merged